# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: "2025 smdn <smdn@smdn.jp>"

# ref: https://docs.github.com/repositories/releasing-projects-on-github/automatically-generated-release-notes
changelog:
  categories:
    - title: Notable changes (may include changes not directly related)
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies
